phockup.py, readme.md, snapcraft.yaml
Resolving this issue https://github.com/ivandokov/phockup/issues/15
=> Add move flag.

.gitignore
This pull request updates the .gitignore file with entries from [Python.gitignore](https://github.com/github/gitignore/blob/master/Python.gitignore)
=> Update .gitignore based on Python.gitignore

phockup.py, tests.py
Add a regex for custom filename date extraction. Closes #22
=> Custom regex

phockup.py, readme.md, snapcraft.yaml, tests.py
Hello,
I added a new feature: creating hard links to source files.
It is useful if you have one good structure and you want to have this year/month/day structure but you don't want to occupy twice much space.
If you use `-l | --link`, you will have new "view" on your photos.
Signed-off-by: Matej Dujava <mdujava@gmail.com>
=> added `-l | --link` flag

phockup.py, readme.md, src/date.py, src/help.py, src/phockup.py, tests/test_date.py
Implements #51. More info on `readme.md` or `help.py`.
=> Add --date-field option to set date extraction fields

src/exif.py
=> Fix filename quoting when shelling out

src/date.py, src/exif.py, src/phockup.py, tests/test_phockup.py
Avoid using the built-ins names for variable names.
=> replace all built-in names

readme.md
Readme updated on request. I have also taken the liberty of adding dry-run flag description.
=> Added info about two flags (quiet/dry-run)

.github/workflows/all-lints.yml, phockup.py, readme.md, src/date.py, src/dependency.py, src/exif.py, src/phockup.py
As promised:
Added lint check's via github action. I added flake8 and isort on top of this I added the All lints status badge if the build was ok. The readme.md is also update with this information.
=> Added lint check's via github action.

Dockerfile, readme.md
- Use latest Python, dropping patch
- Remove build deps after install
- Remove source tar
- Set entrypoint to simplify
=> Docker improvements

phockup.py, readme.md, requirements-dev.txt, src/phockup.py, tests/test_phockup.py
Added the feature progressbar, see ivandokov#21
I used https://github.com/tqdm/tqdm for the progressbar
In addition the readme.md modified with documentation for the progressbar. Also small mistakes in the readme.md have been fixed.
=> Added the feature progressbar

src/phockup.py, tests/test_phockup.py
Split error message on error of input_dir
=> Improve check_directories output on error

.github/workflows/lint.yml, .github/workflows/tests.yml
- Lint 
- Should be run against pull requests
- We shouldn't exclude types and pre-commit lints more now 😄 
- Test
- Could be relaxed but I see no harm in keeping, esp considering tests are fast
=> Tidy on conditions for lint and test pipelines

.github/workflows/deploy.yml
Should resolve #160 
Tested on my fork https://github.com/inverse/phockup/actions/runs/3185437163/jobs/5195006512
=> Fix deploy for buildx

Dockerfile
Upgrade Docker image to use latest Python version
=> Use Python 3.10 for Docker

.github/workflows/dependabot.yml
Add dependabot to bump pip + GitHub actions dependencies
=> Add dependabot to project

.github/workflows/tests.yml
- Add 3.10 to the matrix 
- Wrap versions in quotes
=> Add Python 3.10 to matrix tests

.pre-commit-config.yaml
Bump pre-commit packages to latest versions
=> Bump pre-commit packages

.github/workflows/tests.yml, tests/test_date.py
Fixed linting issues introduced with #181
=> Fix CI issues

readme.md
This improves the documentation as requested in #197
=> Improve documentation of Docker execution modes
