phockup.py

Program aborts execution with an exception if the date attribute is missing:
Traceback (most recent call last):
File "phockup.py", line 263, in <module>
main(sys.argv[1:])
File "phockup.py", line 37, in main
handle_file(os.path.join(root, filename), outputdir)
File "phockup.py", line 181, in handle_file
output_dir = get_output_dir(date, outputdir)
File "phockup.py", line 125, in get_output_dir
'%04d' % date['date'].year,
AttributeError: 'NoneType' object has no attribute 'year'

Execution will continue even if date attribute not present.

---

readme.md

/opt ususally requires root permission
release filename missing letter v

Fix readme instructions

---

phockup.py

Remove "subprocess" import because it is not necessary.

Remove unneeded import

---

phockup.py
readme.md
src/date.py
src/help.py
src/phockup.py
tests/test_date.py

hi! thanks for this useful project. i used it to cleanup a whole lot of old photos i had.  many of them didn't have EXIF data or had the wrong data, but the file timestamps (despite being very old) were in most cases good enough for my needs so I added an option to use the file timestamp if EXIF data isn't there (or can't be used).  I wanted to make it optional since I know there are definitely times when you wouldn't want to use this, especially when those timestamps may not be correct (which is why EXIF data is used first), but I think this could be useful for others too.

v1.5.5: add option for using filestamp

---

tests/test_phockup.py

The test_process_image_unknown unit test triggers an error on case sensitive platforms, like Linux:
```
=============================================================================== FAILURES ================================================================================
______________________________________________________________________ test_process_image_unknown _______________________________________________________________________
mocker = <pytest_mock.MockFixture object at 0x7fe3b0a3c668>
def test_process_image_unknown(mocker):
shutil.rmtree('output', ignore_errors=True)
mocker.patch.object(Phockup, 'check_directories')
mocker.patch.object(Phockup, 'walk_directory')
exif = {"input/UNKNOWN.jpg": {
"MIMEType": "image/jpeg"
}}
Phockup('input', 'output').process_file(exif, …
```

Fix a unit test for case-sensitive filesystems

---

src/date.py

I took a look on issue #39 and it seems to be part of a bug, part user fault. 
The bug was in the `build` function of `Date` objects, that could not handle missing hour/minute/second information from the filename, like the filename in the referenced issue "**img-20161026-wa0011.jpg**", at least on Linux.
The user fault was to write `-r=`  with a "=" in the command. Valid syntaxes are `-r <value>`,  `--regex=<value>` or  `--regex <value>`. Using Anything after the -r" is taken as part of <value> and then the regex would starts with an "=" and fail. 
After correcting the command, the date would have being extracted, but the bug in build function would avoid it to be correctly used.
I could have fixed the issue right in the `from_filename` function (where regex is used)  instead of the …

Fix regex support for incomplete time on filename

---

src/date.py
tests/test_date.py

Fixes #61 
When doing `groupdict` to get the regex information from a filename as a dictionary, the default value of a match is set to 0 so the program won't crash.

Handle regex with optional hour information

---

phockup.py
src/help.py
src/phockup.py
tests/test_phockup.py

Proposal for #67 : `-y` or `--dry-run` cause the same output as a normal run, but don't move, copy or link any files.

Dry run option

---

src/exif.py

Fixes #70, the issue appears to have been that Windows CMD needs the file argument to exiftool be double quoted, single quoting doesn't work.

Fix for #70 1.5.8 not working in Windows

---

phockup.py
src/phockup.py
src/printer.py

I added option "-q", "--quiet" to run phockup without output. I think this is a useful addition.

Added quiet mode to not show output.

---

phockup.py
src/date.py
src/dependency.py
src/exif.py
src/phockup.py

As promised:
Python 3's f-Strings updated to improved String Formatting Syntax.
I have also tried to adhere to the following as much as possible:
_Use single-quotes for string literals, e.g. 'my-identifier', but use double-quotes for strings that are likely to contain single-quote characters as part of the string itself (such as error messages, or any strings containing natural language), e.g. "You've got an error!".
Single-quotes are easier to read and to type, but if a string contains single-quote characters then double-quotes are better than escaping the single-quote characters or wrapping the string in double single-quotes._

Python 3's f-Strings updated to improved String Formatting Syntax.

---

.github/workflows/tests.yml
Dockerfile

I realised that the copying of the `latest` isn't what's committed to master. 
Having it this way will also aid development since it copies in the code into the container. 
```bash
docker build -t phockup:local .
```

Simplify DockerFile + add CI build

---

readme.md

Thanks for this tool :)
I saw "skipped, duplicated file X" in the output and it was unclear to me if this was simply based on filename or on file contents. I found something about this in the issue tracker (https://github.com/ivandokov/phockup/issues/112) and I thought it would be useful to add this to the README.

Add paragraph on duplicate handling in README.

---

phockup.py
readme.md
src/date.py

Added support for parsing 'W' and 'U' as optional week of the year formats.
As requested in https://github.com/ivandokov/phockup/issues/85
Opted to only support it on the output format rather and not on the file name parsing RegEx.  Seemed awkward to parse "date" information that may only contain a week of the year if the output was a `YYYY/MM/DD` format.
Updated command line and readme documentation

Initial implementation of "this week in pictures"

---

phockup.py
src/phockup.py
tests/test_phockup.py

Initial implementation of https://github.com/ivandokov/phockup/issues/74 
Allows user to specify where Unknown date files go via a command line parameter.  Parameter `--no-date-dir` overrides the default of "unknown".  
`phockup INPUTDIR OUTPUTDIR --no-date-dir=UNKNOWNDIR`
`phockup ~/Pictures/camera ~/Pictures/sorted --no-date-dir=Miscellaneous `
This would put all files without valid EXIF date information in the `~/Pictures/sorted/Miscellaneous` directory.
Also included: 
- Added pytest use case named `test_no_exif_directory` for alternative `unknown` directory name testing.
- Refactored phockup constants to the Phockup class ease of scoping for imports and tight coupling to the class. 
`DEFAULT_DIR_FORMAT = ['%Y', '%m', '%d']`
`DEFAULT_NO_DATE_DIRECTORY = "unknown"`
- Implemented the …

Initial implementation of Allowing Unknown Images directory naming

---

src/phockup.py

Replacing `checksum()` method with native `filecmp.cmp()` method to leverage inherent caching of checksums for comparison (particularly with large duplicate data sets).  Defaulted to `shallow=False` due to paranoia.
See https://docs.python.org/3/library/filecmp.html
I came across this option when doing a lot of network copies with lots of duplicates.  This implementation seems to improve throughput on comparisons for a large number of duplicate files.  
Below is a simple test, but the speed improvement was enough to compel me to make this PR.  Note that due to network and computer issues, the `filecmp.cmp()` version took longer, but spent less time comparing files.  If I could create a local test case that had consistent numbers, I would.  But I figured the ~30% reduction in comparison …

Replace checksum method with native filecmp.cmp() method

---

phockup.py
src/date.py
src/phockup.py
tests/test_phockup.py

Implemented --skip-unknown flag to leave files without matching EXIF data in place.
Added test_skip_unknown test to the harness
This has proved useful to me when the folder structure contains metadata that I can use to process images on the second or third pass with additional flags.  Having them moved to a single folder loses the taxonomy that the images may have, so having them stay in place is useful to me.
See Issue #79 for additional details.

Address Issue #79 to skip "Unknown" files (based on EXIF data)

---

src/phockup.py

I found this tool useful for organizing a folder I previously used phockup in. In that case, both source and destination directories are the same. since the directories are the same, it tried to move every file into itself and check the checksums if they are equivalent. We can skip the checksum since we know it's the same file since they have the same paths. This would greatly speed up reorganizing a directory.

Skip checksum when reorganizing folder

---

entrypoint.sh
src/phockup.py

Allows for concurrent threads to attempt to create the same directory without throwing an exception if another thread creates it first.  Most frequently occurs when using multiple threads and network shares with phockup (now I tested).  This fix alleviates the collision created by the 'slow' folder creation across networks that was throwing exceptions.
Fix was to add `exists_ok=True` to the `os.mkdirs()` call on missing target directories.
See https://github.com/ivandokov/phockup/issues/149

Allowed for duplicate target paths to exist for mkdirs 

---

phockup.py
readme.md
src/phockup.py
tests/test_phockup.py

Addresses #146 
Adding support for output directory prefix and suffix support to aid in storing files with an additional layer of taxonomy.  
- Added `--output-prefix` command line argument support
- Added `--output-suffix` command line argument support
- Updated `get_output_dir` to support assembling directory paths with prefix and/or suffix parameters
- Updated 'unknown' folder support to include prefix and suffix directives when storing files with unknown date information.
- Updated `--skip-unknown` to support directories other than "unknown" when specified via the `--no-date-dir` argument
- Implemented test cases for prefix, suffix, and prefix+suffix
- Refactored `validate_copy_operations` to support prefix and suffix tests
See readme for details on use cases for prefix and suffix

Implementation of Issue #146 to support prefix and suffix

---

readme.md

Doing my duty as the original contributor and documenting the feature as requested in #184.
This work duplicates that done in #186, but I figured I'd take the opportunity to detail its usage since it's a bit more wonky than a regular flag.
Open to suggestions/corrections/recommendations

Details regarding usage of --max-concurrency

---

entrypoint.sh

See also https://www.shellcheck.net/wiki/SC2068, especially setting multiple whitespace separated date-fields is now possible when using the container.

Make sure arguments are not split

---

readme.md

#197 
When I ran the one shot docker command for the first time I started with the example in the documentation. While this worked there was some confusion as the Dockerfile will create `/mnt/input` and `/mnt/output` automatically. With this PR this behaviour doesn't change but is less noticeable.

Update documentaion to match folders created in Docker file

---

phockup.py

Currently `--help` is busted because python is interpreting %U as a format character. Fix it.
Before:
```
~> docker run phockup --help
unsupported format character 'U' (0x55) at index 297
```
After:
```
~> docker run phockup --help
usage: phockup [-h] [-v] [-d DATE] [-m | -l] [-o] [-t] [-y] [-c 1-255]
[--maxdepth 1-255] [-r REGEX] [-f DATE_FIELD]
[--debug | --quiet | --progress] [--log LOG]
[--file-type image|video] [--no-date-dir NO_DATE_DIR]
[--skip-unknown] [--output_prefix OUTPUT_PREFIX]
[--output_suffix OUTPUT_SUFFIX]
INPUTDIR OUTPUTDIR
Media sorting tool to organize photos and videos from your camera in folders by year, month and day.
The software will collect all files from the input directory and copy them to the output
directory without changing the files content. It will only …
```

Fix --help printing

---

phockup.py
readme.md
src/phockup.py
tests/test_phockup.py

This PR adds `from_date` and `to_date` command line options to limit the file processing based on the calculated data. Files with unknown date are unfiltered.
This is useful to me because I have a sync folder where the phones keep dumping the data so deleted pictures will be recreated.
I use phockup to copy the pics to a nice structure and then select the ones that I want to keep, so reprocessing all the source folder would replace the photos that I deleted.

Adde from_date and to_date options to limit the processed files

---

phockup.py
src/phockup.py
tests/test_phockup.py

Implement `move or delete` option: if both `move` and `skip_unknown` are enabled, adding this flag will cause the source file to be deleted.  This addition enables merging multiple redundant libraries into one.

implement movedel

---

phockup.py
src/phockup.py
tests/test_phockup.py

closes https://github.com/ivandokov/phockup/issues/20 as option, not by default.
Adds an option --rmdirs which will delete empty subdirectories after processing with --move is complete. Respects --maxdepth.

implement --rmdirs option
